### ISSUE TITLE
I cant seem to install it for my Vtiger 6.o

### ISSUE THREAD

**Issue by Yasser75** [tsolucio/Timecontrol#2]
dUnzip2: File 'manifest.xml' is not compressed in the zip.
Warning: simplexml_load_file(): I/O warning : failed to load external entity "test/vtlib/manifest-1424264820.xml" in C:\Program Files\vtigercrm600\apache\htdocs\vtigerCRM\vtlib\Vtiger\PackageImport.php on line 54 Warning: unlink(test/vtlib/manifest-1424264820.xml): No such file or directory in C:\Program Files\vtigercrm600\apache\htdocs\vtigerCRM\vtlib\Vtiger\PackageImport.php on line 55 dUnzip2: File 'manifest.xml' is not compressed in the zip.
Warning: simplexml_load_file(): I/O warning : failed to load external entity "test/vtlib/manifest-1424264820.xml" in C:\Program Files\vtigercrm600\apache\htdocs\vtigerCRM\vtlib\Vtiger\PackageImport.php on line 54 Warning: unlink(test/vtlib/manifest-1424264820.xml): No such file or directory in C:\Program Files\vtigercrm600\apache\htdocs\vtigerCRM\vtlib\Vtiger\PackageImport.php on line 55

**Comment by joebordes** [comment]
Hi,

I have to say that vtiger CRM 6 is a totally new application, it has nothing to do with the 5.x branch. It is like going to Zurmo or SuiteCRM. It is like you went from Drupal to Joomla or from OpenERP to ApacheOfBiz, but worse because at least the previous examples are tested well documented projects, while vtiger 6 now needs to start debugging the whole new code base! (they are trying to fix and update everything, and also they had to take down the market place because none of the modules were compatible). All our knowledge and effort has been basically thrown away and the users have to learn a new interface when they are currently productive in the one they have. The difference is so big that we have changed our mind and decided to stop supporting VT6 and created the coreBOS project (http://corebos.org) where we will give life to the 5.x base and where both developers and users can evolve without having to learn something new. It is a continuity, a project you can count on to be there and adapt to future needs while leveraging your current investment.

I truly hope to see you join us in this adventure but I, totally respect your decision to go with VT6, I am also positive that in the end it will be a good product too.

This module and it's future development will not support VT6.

Let me know if you have any questions and I invite you to follow us on G+ and/or linkedin.

Joe
TSolucio
